ignore:
    - "test_*.py"
    - "**/tests/**"
flag_management:
    individual_flags:
        - name: client
          paths:
              - "client/"
        - name: backend
          paths:
              - "backend/"
