ignore:
    - "test_*.py"
    - "**/tests/**"
    - "*_test.go"
coverage:
    status:
        project: off
        patch: off
flag_management:
    individual_flags:
        - name: client
          paths:
              - "client/"
          carryforward: true
        - name: backend
          paths:
              - "backend/"
          carryforward: true
        - name: watcher
          paths:
              - "watcher/"
          carryforward: true
