[tool.ruff]
preview = true

[tool.ruff.lint]
select = ["E", "F", "I", "W", "B", "UP", "C4", "PYI", "FAST"]
ignore = [
  "E501",   # Line too long
  "RUF029", # Unused Async (FastAPI routes are async)
]
