---
# Source: ray-cluster/templates/raycluster-cluster.yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  labels:
    helm.sh/chart: ray-cluster-1.1.0
    app.kubernetes.io/instance: raycluster
    app.kubernetes.io/managed-by: Helm
    kueue.x-k8s.io/queue-name: user-queue
  name: raycluster-kuberay

spec:
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        imagePullSecrets: []
        containers:
          - volumeMounts:
              - mountPath: /tmp/ray
                name: log-volume
            name: ray-head
            image: rayproject/ray:2.9.0-gpu
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: "1"
                memory: 2G
              requests:
                cpu: "1"
                memory: 2G
            securityContext: {}
            env:

        volumes:
          - emptyDir: {}
            name: log-volume
        affinity: {}
        tolerations: []
        nodeSelector: {}
      metadata:
        annotations: {}
        labels:
          helm.sh/chart: ray-cluster-1.1.0
          app.kubernetes.io/instance: raycluster
          app.kubernetes.io/managed-by: Helm

  workerGroupSpecs:
    - rayStartParams: {}
      replicas: 1
      minReplicas: 1
      maxReplicas: 1
      numOfHosts: 1
      groupName: workergroup
      template:
        spec:
          imagePullSecrets: []
          containers:
            - volumeMounts:
                - mountPath: /tmp/ray
                  name: log-volume
              name: ray-worker
              image: rayproject/ray:2.9.0-gpu
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "1"
                  memory: 1G
                  nvidia.com/gpu: 1
                requests:
                  cpu: "1"
                  memory: 1G
                  nvidia.com/gpu: 1
              securityContext: {}
              env:
              ports: null

          volumes:
            - emptyDir: {}
              name: log-volume
          affinity: {}
          tolerations: []
          nodeSelector: {}
        metadata:
          annotations: {}
          labels:
            helm.sh/chart: ray-cluster-1.1.0
            app.kubernetes.io/instance: raycluster
            app.kubernetes.io/managed-by: Helm
