apiVersion: skaffold/v4beta11
kind: Config
metadata:
    name: backend
build:
    artifacts:
        - image: ghcr.io/aai-institute/jobq-server
          docker:
              dockerfile: Dockerfile
deploy:
    helm:
        releases:
            - name: jobq-server
              chartPath: deploy/jobq-server
              valuesFiles:
                  - deploy/jobq-server/values.yaml
              version: 0.1.0
