name: Install Python dependencies
description: Install all core and optional Python dependencies
inputs:
    pythonVersion:
        description: Python version to set up (see actions/setup-python@v5)
        required: true
    workingDirectory:
        description: Working directory (from which requirements files are read)
        required: false
        default: "."
runs:
    using: "composite"
    steps:
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.pythonVersion }}
        - name: Install Python dependencies
          working-directory: ${{ inputs.workingDirectory }}
          run: |
              pip install -U pip uv
              uv venv
              uv pip install -r requirements-dev.txt
              uv pip install --no-deps .
          shell: bash
