name: Python lint
description: Set up a Python project and perform basic linter checks (through pre-commit)
inputs:
    pythonVersion:
        description: Python version to set up (see actions/setup-python@v5)
        required: true
    workingDirectory:
        description: Working directory (from which requirements files are read)
        required: false
        default: "."
runs:
    using: "composite"
    steps:
        - name: Set up Python and dependencies
          uses: ./.github/actions/python-deps
          with:
              pythonVersion: "${{ inputs.pythonVersion }}"
              workingDirectory: ${{ inputs.workingDirectory }}
        - name: Run pre-commit checks
          run: uvx pre-commit run --all-files --verbose --show-diff-on-failure
          shell: bash
