name: Python lint
description: Set up a Python project and perform basic linter checks (through pre-commit)
inputs:
  pythonVersion:
    description: Python version to set up (see actions/setup-python@v5)
    required: true
  workingDirectory:
    description: Working directory (from which requirements files are read)
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Set up Python and dependencies
      uses: ./.github/actions/python-deps
      with:
        pythonVersion: "${{ inputs.pythonVersion }}"
        workingDirectory: ${{ inputs.workingDirectory }}
    - name: Cache pre-commit tools
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.MYPY_CACHE_DIR }}
          ${{ env.RUFF_CACHE_DIR }}
          ${{ env.PRE_COMMIT_HOME }}
        key: ${{ hashFiles(format('{0}/requirements-dev.txt', inputs.workingDirectory), '.pre-commit-config.yaml') }}-linter-cache
    - name: Run pre-commit checks
      run: pre-commit run --all-files --verbose --show-diff-on-failure
      shell: bash
