name: "Backend: Python"

on:
    push:
        branches:
            - main
    pull_request:
        paths:
            - backend/**
            - .github/**
        branches:
            - main

defaults:
    run:
        working-directory: backend

jobs:
    lint-and-test:
        name: Test jobq-server on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python: [ "3.11" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
              uses: ./.github/actions/python-deps
              with:
                  pythonVersion: ${{ matrix.python }}
                  workingDirectory: "backend"
            - uses: ./.github/actions/python-lint
              with:
                  pythonVersion: ${{ matrix.python }}
                  workingDirectory: "backend"
            - name: Execute python tests
              run: uv run pytest -s --cov=src --cov-report=xml --junitxml=junit.xml
            - name: Upload results to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./backend/coverage.xml
                  slug: aai-institute/jobq
                  flags: backend
            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./backend/junit.xml
                  slug: aai-institute/jobq
                  flags: backend
