name: "Client library: Python"

on:
    push:
        branches:
            - main
    pull_request:
        paths:
            - client/**
            - .github/**
        branches:
            - main

defaults:
    run:
        working-directory: client

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/python-lint
              with:
                  pythonVersion: "3.11"
                  workingDirectory: client
    test:
        name: Test jobs-infra on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python: [ "3.10" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
              uses: ./.github/actions/python-deps
              with:
                  pythonVersion: ${{ matrix.python }}
                  workingDirectory: "client"
            - name: Execute python tests
              run: uv run pytest -s --cov=src --cov-report=xml --junitxml=junit.xml
            - name: Upload results to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./client/coverage.xml
                  slug: aai-institute/jobq
                  flags: client
            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./client/junit.xml
                  slug: aai-institute/jobq
                  flags: client
