name: Lint and test jobs poc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      MYPY_CACHE_DIR: "${{ github.workspace }}/.cache/mypy"
      RUFF_CACHE_DIR: "${{ github.workspace }}/.cache/ruff"
      PRE_COMMIT_HOME: "${{ github.workspace }}/.cache/pre-commit"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e . --no-deps
      - name: Cache pre-commit tools
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.MYPY_CACHE_DIR }}
            ${{ env.RUFF_CACHE_DIR }}
            ${{ env.PRE_COMMIT_HOME }}
          key: ${{ hashFiles('requirements.txt', '.pre-commit-config.yaml') }}-linter-cache
      - name: Run pre-commit checks
        run: pre-commit run --all-files --verbose --show-diff-on-failure
  test:
    name: Test jobs-infra on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up oldest supported Python on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Run tests on oldest supported Python
      run: |
        python -m pip install -r requirements.txt
        python -m pip install .
        pytest
